### ISSUE TITLE
User Friendly Code

### ISSUE THREAD

**Issue by sahilrider** [sahilrider/Python-Functions#1]
Write comments for better understanding of the code

**Comment by DavidJaimesDesign** [comment]
Can I grab this one?

**Comment by sahilrider** [comment]
Let me explain this issue.
 I want simpler code , user friendly with less time complexity and well commented.

Don't just create PR for commenting on the code.

**Comment by DavidJaimesDesign** [comment]
Ooooh I think I understand now. So then for the refactor do you want input validation?
